runtime: python27
api_version: 1
threadsafe: true
instance_class: B1
service: default
basic_scaling:
  max_instances: 1
  idle_timeout: 5m

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app